const express = require('express');
const router = express.Router();
const Groq = require('groq-sdk');
const Analysis = require('../models/Analysis');

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

const SYSTEM_PROMPT = `You are SlopSweep, an expert AI content quality analyst. Your job is to determine whether a piece of text is "AI slop" — low-quality, generic, repetitive, or substance-free content typically generated by AI models with minimal human oversight.

Evaluate the text based on these criteria:
1. **Vagueness**: Does the text make broad claims without specific examples, data, or concrete details?
2. **Filler Language**: Does it overuse transitional phrases like "In today's world", "It's important to note", "Furthermore", "In conclusion"?
3. **Circular Logic**: Does the text repeat the same idea in slightly different words without adding new information?
4. **Robotic Neutrality**: Does it avoid taking any real stance, hedging every statement?
5. **Listicle Padding**: Does it use numbered lists or bullet points that say obvious things just to fill space?
6. **Cliché Density**: Does it rely heavily on overused phrases like "game-changer", "at the end of the day", "leverage", "unlock potential"?

You MUST respond with ONLY valid JSON in this exact format, no markdown, no code fences:
{
  "slop_score": <number from 0 to 100>,
  "reasoning": "<2-4 sentence explanation of your assessment>",
  "flagged_phrases": ["<phrase1>", "<phrase2>"],
  "verdict": "<one of: authentic, suspicious, slop>"
}

Scoring guide:
- 0-30: authentic (genuine human writing with substance)
- 31-70: suspicious (has some AI-like patterns but may be human)
- 71-100: slop (almost certainly low-effort AI-generated filler)`;

// POST /api/analyze
router.post('/', async (req, res) => {
  try {
    const { text } = req.body;

    if (!text || text.trim().length === 0) {
      return res.status(400).json({ success: false, error: 'Text is required.' });
    }

    if (text.length > 10000) {
      return res.status(400).json({ success: false, error: 'Text exceeds maximum length of 10,000 characters.' });
    }

    const chatCompletion = await groq.chat.completions.create({
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: text }
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.3,
      response_format: { type: "json_object" }
    });

    const responseText = chatCompletion.choices[0].message.content;
    let parsed;

    try {
      parsed = JSON.parse(responseText);
    } catch (parseErr) {
      console.error('Failed to parse Groq response:', responseText);
      return res.status(500).json({
        success: false,
        error: 'AI returned an unexpected format. Please try again.',
      });
    }

    // Save to MongoDB
    const analysis = await Analysis.create({
      text_preview: text.substring(0, 500),
      slop_score: parsed.slop_score,
      reasoning: parsed.reasoning,
      flagged_phrases: parsed.flagged_phrases || [],
      verdict: parsed.verdict,
    });

    return res.status(200).json({
      success: true,
      data: {
        _id: analysis._id,
        slop_score: parsed.slop_score,
        reasoning: parsed.reasoning,
        flagged_phrases: parsed.flagged_phrases || [],
        verdict: parsed.verdict,
      },
    });
  } catch (error) {
    console.error('Analysis Error:', error.message);

    // Groq rate limit errors
    if (error.status === 429 || error.message.includes('429')) {
      return res.status(429).json({
        success: false,
        error: 'Rate limit reached. Please wait a moment and try again.',
      });
    }

    return res.status(500).json({
      success: false,
      error: 'An error occurred during analysis: ' + error.message,
    });
  }
});

// GET /api/analyze/history - Fetch recent analyses
router.get('/history', async (req, res) => {
  try {
    const analyses = await Analysis.find()
      .sort({ createdAt: -1 })
      .limit(20)
      .select('-__v');
    return res.status(200).json({ success: true, data: analyses });
  } catch (error) {
    console.error('History Error:', error.message);
    return res.status(500).json({ success: false, error: 'Failed to fetch history.' });
  }
});

module.exports = router;
